{
    "meta":{
        "success":true,
        "message":"操作成功"
    },
    "data":{
        "versionNum":"00.00.0003",
        "updatetime":1529913235037,
        "versionInformation":"2",
        "ipIos":"1",
        "ipAndroid":"2"
    }
}